# Site settings
title: "Wenchao's Webpage"
description: "Personal webpage"
baseurl: ""
url: "https://bai-wenchao.github.io"

# Personal info
author:
  name: "Wenchao Bai"
  title: "Ph.D. Candidate"
  email: "wbai@seu.edu.cn"
  affiliation: "Southeast University"
  department: "Department of Computer Science and Engineering"

# Social links
social:
  google_scholar: "https://scholar.google.com/citations?user=DurVj1gAAAAJ&hl=en"
  orcid: "https://orcid.org/0009-0001-1632-4347"
  github: "https://github.com/bai-wenchao"
  linkedin: "https://www.linkedin.com/in/wenchao-bai-959992274/"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - README.md

# SEO settings
twitter:
  username: your_twitter
  card: summary

facebook:
  app_id: ""
  publisher: ""
  admins: ""

logo: "/assets/images/profile-photo.jpg"